### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by Kyvrel** [flytrap/bwg-api#1]
`pip install bwg-api`出错：
```
Looking in indexes: https://pypi.douban.com/simple
Collecting bwg-api
  Downloading https://pypi.doubanio.com/packages/41/81/6ec60005168badbf3ee63a156fb3c639edfa6a31612eba614036ec6aab94/bwg-api-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-73lk46tq/bwg-api/setup.py", line 6, in <module>
        from bwg.bwg_api import BWG
      File "/tmp/pip-install-73lk46tq/bwg-api/bwg/bwg_api.py", line 7, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-73lk46tq/bwg-api/
```

手动安装`requests`后，才能安装成功

**Comment by flytrap** [comment]
已更新，谢谢
